# Domain-specific configuration
# Add custom settings for specific domains

domains:
  # Example configurations
  wikipedia.org:
    delay: 0.5                    # Faster for Wikipedia
    selectors:
      table: "table.wikitable"    # Wikipedia-specific table class
    
  example.com:
    delay: 2.0                    # Slower for this domain
    user_agent: "Custom User Agent for Example"
    headers:
      Accept: "text/html,application/json"
      Accept-Language: "en-US,en;q=0.9"
    
  # Sports sites
  espn.com:
    delay: 1.5
    subdomain_organization: true  # Organize by subdomain (nba/, nfl/, etc.)
    selectors:
      standings: "table.standings-table"
      scores: "div.score-container"
      
  nba.com:
    delay: 1.0
    selectors:
      stats: "table.stats-table"
      standings: "table.standings"
      
  # News sites often require different handling
  reuters.com:
    delay: 2.0
    cache_ttl: 1800  # 30 minutes for news
    
  bloomberg.com:
    delay: 2.5
    cache_ttl: 1800
    
# Rate limit groups
# Sites in the same group share rate limiting
rate_limit_groups:
  news:
    domains: ["reuters.com", "bloomberg.com", "cnn.com"]
    delay: 2.0
    max_concurrent: 2
    
  sports:
    domains: ["espn.com", "nba.com", "nfl.com"]
    delay: 1.5
    max_concurrent: 3