# Domain-specific rate limiting configuration
# Add domains that require special handling

rate_limits:
  # Sports sites often have strict rate limits
  basketball-reference.com: 10.0  # 10 seconds between requests (increased due to 429 errors)
  www.basketball-reference.com: 10.0
  baseball-reference.com: 2.0
  www.baseball-reference.com: 2.0
  pro-football-reference.com: 2.0
  www.pro-football-reference.com: 2.0
  hockey-reference.com: 2.0
  www.hockey-reference.com: 2.0
  
  # News sites
  cnn.com: 1.0
  bbc.com: 1.0
  nytimes.com: 1.5
  
  # E-commerce
  amazon.com: 2.0
  ebay.com: 1.5
  
  # APIs and data sources
  api.github.com: 0.5
  api.twitter.com: 1.0
  
# Excluded URL patterns (regex)
excluded_patterns:
  - ".*\\/(login|signin|register|logout).*"
  - ".*\\.pdf$"
  - ".*\\/(ads?|advertisement).*"
  - ".*\\/(share|print|email).*"
  - ".*\\#comment.*"
  - ".*utm_.*"
  - ".*fbclid=.*"

# User agents for specific domains
user_agents:
  default: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  basketball-reference.com: "Mozilla/5.0 (compatible; MasterDataScraper/1.0; +https://github.com/yourusername/master-data-scraper)"